### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tsndp** [amir9480/vscode-laravel-extra-intellisense#13]
I have installed this, but its not working as shown in gif. are there any other dependencies to this extension in vscode?

**Comment by amir9480** [comment]
What gif?

You can show errors in 
`Help > Toggle Developer Tools > console`. 
Your laravel application should have no errors and exceptions while running Artisan commands.
For example, check `php artisan route:list` works properly.

**Comment by jozefcuryllo** [comment]
I also had some problems to make it working. As far as I know you should take care that:
- you have already installed and enabled "PHP IntelliSense" extension,
- you have installed your dependencies (composer install/update) (?)
- your files have been already parsed by "PHP IntelliSense" (at least in some part?)
- then most likely you should reload your VS Code.

Also please make sure that you have php installed globally (I mean that command "php" is executable - I think it's not possible at the moment to change the path of executable php). Your Laravel project should also be as "standard" as possible (don't really change the folder structure).

I think, that info should be written in the main page, because it's not so obvious. And of course, correct me if I'm wrong - maybe some of the steps are not really necessary.

**Comment by bagusk99** [comment]
> What gif?
> 
> You can show errors in `Help > Toggle Developer Tools > console`. Your laravel application should have no errors and exceptions while running Artisan commands. For example, check `php artisan route:list` works properly.

Wow thank you, now my plugin work perfectly. I'm not installing php in my local machine, because i'm using docker and when i open the console, it's says php not found, so i tried to install php in my local machine and now my plugin working properly, thank you so much.
