### ISSUE TITLE
How to use this extension with sail?

### ISSUE THREAD

**Issue by exSnake** [amir9480/vscode-laravel-extra-intellisense#83]
It was working but now, suddently, after writing ```route("")``` only dusk route pop-ups. I'm using Laravel Sail and saw in the documentation that for Laradock you should edit the  LaravelExtraIntellisense.phpCommand, i' ve tried to make it work like this

```"LaravelExtraIntellisense.phpCommand": "sail php -r \"{code}\""```

but didn't expericed any results, route still missing and in the console nothing seems to be relevant to this extension.

**Comment by walirazzaq** [comment]
@exSnake did you find any solution to this?

**Comment by ljubadr** [comment]
When using docker container most of the extensions need `command` changed to run the command inside the docker container. While I managed to setup `command` for most of the extensions that I use there were always few that I never managed to set up. That's why I switched to [Developing inside a Container](https://code.visualstudio.com/docs/devcontainers/containers) and it works great. Most of the time you don't even need to change anything and extensions just work

Possible issue could be that you are trying to use `alias` that vscode is not seeing. You could try to use 

```
./vendor/bin/sail php -r "{code}"
# OR
sh vendor/bin/sail php -r "{code}"
```

You could also try to use directly `docker-compose`

```
docker-compose exec --user=sail <service-name> php -r "{code}"
```

**Comment by ctf0** [comment]
u can also use 
```
"LaravelExtraIntellisense.phpCommand": "/usr/local/bin/docker exec <service-name> php -r \"{code}\"",
```

this is the same as using `sail shell` then running the command directly on the image.
